upgraded demo app to support latest appwrite version
appwrite/demo-almost-netflix-for-web pull request #2
Opened 2022-10-06 00:02 UTC by DevTomilola-OS

## What does this PR do?

Upgrades demo app code to support appwrite latest version.

## Test Plan
I ran the necessary commands and was able to use the demo app locally.

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2022-10-11 13:50 UTC, codercatdev requested changes
See changes requested.

2022-10-11 13:50 UTC, codercatdev commented on .gitignore
> +package-lock.json
@DevTomilola-OS the `package-lock` should be left so that we are testing against the same versions each time.

2022-10-11 13:50 UTC, codercatdev commented on services/appwrite.ts
> +const databases = new Databases(client);
Please check lines for databases, in v1.0 they must specify databaseId like `almost-netflix-project-db`

```diff
-await databases.listDocuments<AppwriteMovie>("movies", "trendingIndex", ["DESC"]);
+await databases.listDocuments<AppwriteMovie>("almost-netflix-project-db","movies", "trendingIndex", ["DESC"]);
```

I have updated the seed project so you have a good working example of this 

https://github.com/Meldiron/almost-netflix-project-setup/blob/cacc3974a625411d97c4efc5a1e33c8228a3f08f/src/migrations.js#L125

2022-10-11 14:49 UTC, DevTomilola-OS commented
Working on it @codercatdev

2022-10-31 16:20 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2023-01-18 07:57 UTC, christyjacob4 commented
@DevTomilola-OS please address the comments

2023-02-10 21:01 UTC, codercatdev commented
@DevTomilola-OS were you able to make the above change?

2023-04-06 16:24 UTC, christyjacob4 commented
@DevTomilola-OS thanks a lot for your contributions during Hacktoberfest 2022! Since there has been no activity on this PR for a while, we'll be closing it for now. If you'd like to work on it again, please feel free to create a new PR.  

Meanwhile you can reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord. 

2023-04-06 16:24 UTC, closed without merging